import type { Movie } from "@/types/movie";

export const mockMovies: Record<string, Movie[]> = {
  happy: [
    {
      id: 1,
      title: "The Grand Comedy",
      overview: "A hilarious adventure that will make you laugh from start to finish.",
      poster_path: "/public/grand comed.jpeg",
      backdrop_path: null,
      release_date: "2024-05-15",
      vote_average: 8.5,
      vote_count: 1250,
      genre_ids: [35, 10751],
    },
    {
      id: 2,
      title: "Family Fun Time",
      overview: "A family goes on an adventure that brings them closer together through laughter and joy.",
      poster_path: "https://example.com/posters/family_fun_time.jpg",
      backdrop_path: null,
      release_date: "2024-01-10",
      vote_average: 7.8,
      vote_count: 980,
      genre_ids: [35, 10751],
    },
    {
      id: 3,
      title: "Laugh Out Loud",
      overview: "A stand-up comedian finds himself in increasingly absurd situations.",
      poster_path: "https://example.com/posters/laugh_out_loud.jpg",
      backdrop_path: null,
      release_date: "2024-02-28",
      vote_average: 8.2,
      vote_count: 1100,
      genre_ids: [35],
    },
    {
      id: 4,
      title: "Silly Adventures",
      overview: "Four friends embark on a road trip that turns into a series of hilarious mishaps.",
      poster_path: "https://example.com/posters/silly_adventures.jpg",
      backdrop_path: null,
      release_date: "2024-07-22",
      vote_average: 7.5,
      vote_count: 850,
      genre_ids: [35, 12],
    },
  ],
  sad: [
    {
      id: 5,
      title: "Lost Love",
      overview: "A heartbreaking story about love and loss that will move you to tears.",
      poster_path: "https://example.com/posters/lost_love.jpg",
      backdrop_path: null,
      release_date: "2024-04-18",
      vote_average: 8.7,
      vote_count: 1500,
      genre_ids: [18, 10749],
    },
    {
      id: 6,
      title: "Goodbye Forever",
      overview: "Two lovers are separated by circumstances beyond their control.",
      poster_path: "https://example.com/posters/goodbye_forever.jpg",
      backdrop_path: null,
      release_date: "2024-01-05",
      vote_average: 8.3,
      vote_count: 1200,
      genre_ids: [18, 10749],
    },
    {
      id: 7,
      title: "The Last Letter",
      overview: "A dying writer sends one final letter to the love of his life.",
      poster_path: "https://example.com/posters/last_letter.jpg",
      backdrop_path: null,
      release_date: "2024-03-15",
      vote_average: 8.9,
      vote_count: 1650,
      genre_ids: [18, 10749],
    },
    {
      id: 8,
      title: "Fading Memories",
      overview: "A woman struggles with losing her memories of a past relationship.",
      poster_path: "https://example.com/posters/fading_memories.jpg",
      backdrop_path: null,
      release_date: "2024-06-30",
      vote_average: 8.1,
      vote_count: 950,
      genre_ids: [18],
    },
  ],
  thrill: [
    {
      id: 9,
      title: "The Haunting",
      overview: "A family moves into a house with a dark past and begins experiencing terrifying events.",
      poster_path: "https://example.com/posters/haunting.jpg",
      backdrop_path: null,
      release_date: "2024-10-31",
      vote_average: 7.9,
      vote_count: 1100,
      genre_ids: [27, 9648],
    },
    {
      id: 10,
      title: "Night Stalker",
      overview: "A detective hunts a serial killer who only strikes during the full moon.",
      poster_path: "https://example.com/posters/night_stalker.jpg",
      backdrop_path: null,
      release_date: "2024-03-12",
      vote_average: 8.4,
      vote_count: 1300,
      genre_ids: [53, 9648],
    },
    {
      id: 11,
      title: "The Basement",
      overview: "A group of friends discover something horrifying in an abandoned basement.",
      poster_path: "https://example.com/posters/basement.jpg",
      backdrop_path: null,
      release_date: "2024-01-20",
      vote_average: 7.6,
      vote_count: 890,
      genre_ids: [27],
    },
    {
      id: 12,
      title: "Whispers in the Dark",
      overview: "A woman begins hearing voices that lead her to uncover a conspiracy.",
      poster_path: "https://example.com/posters/whispers_in_the_dark.jpg",
      backdrop_path: null,
      release_date: "2024-08-08",
      vote_average: 8.0,
      vote_count: 1050,
      genre_ids: [53, 9648],
    },
  ],
  cry: [
    {
      id: 13,
      title: "Forever Gone",
      overview: "A touching story about saying goodbye to a loved one.",
      poster_path: "https://example.com/posters/forever_gone.jpg",
      backdrop_path: null,
      release_date: "2024-02-14",
      vote_average: 8.8,
      vote_count: 1600,
      genre_ids: [18],
    },
    {
      id: 14,
      title: "The Last Day",
      overview: "A terminally ill man tries to make his last day on Earth meaningful.",
      poster_path: "https://example.com/posters/last_day.jpg",
      backdrop_path: null,
      release_date: "2024-01-25",
      vote_average: 9.1,
      vote_count: 1800,
      genre_ids: [18],
    },
    {
      id: 15,
      title: "Saying Goodbye",
      overview: "A daughter reconnects with her estranged father before it's too late.",
      poster_path: "https://example.com/posters/saying_goodbye.jpg",
      backdrop_path: null,
      release_date: "2024-05-05",
      vote_average: 8.5,
      vote_count: 1250,
      genre_ids: [18],
    },
    {
      id: 16,
      title: "The Journey Home",
      overview: "A soldier returns home to find everything has changed.",
      poster_path: "https://example.com/posters/journey_home.jpg",
      backdrop_path: null,
      release_date: "2024-07-04",
      vote_average: 8.3,
      vote_count: 1150,
      genre_ids: [18, 10752],
    },
  ],
  romantic: [
    {
      id: 17,
      title: "Love at First Sight",
      overview: "Two strangers meet by chance and fall deeply in love.",
      poster_path: "https://example.com/posters/love_at_first_sight.jpg",
      backdrop_path: null,
      release_date: "2024-02-14",
      vote_average: 7.9,
      vote_count: 1050,
      genre_ids: [10749],
    },
    {
      id: 18,
      title: "The Perfect Match",
      overview: "A matchmaker who doesn't believe in love finds herself falling for a client.",
      poster_path: "https://example.com/posters/perfect_match.jpg",
      backdrop_path: null,
      release_date: "2024-06-22",
      vote_average: 7.7,
      vote_count: 950,
      genre_ids: [10749, 35],
    },
    {
      id: 19,
      title: "Summer Romance",
      overview: "A summer fling turns into something more meaningful than either expected.",
      poster_path: "https://example.com/posters/summer_romance.jpg",
      backdrop_path: null,
      release_date: "2024-08-01",
      vote_average: 8.2,
      vote_count: 1100,
      genre_ids: [10749],
    },
    {
      id: 20,
      title: "Across the Distance",
      overview: "Two people maintain a long-distance relationship against all odds.",
      poster_path: "https://example.com/posters/across_the_distance.jpg",
      backdrop_path: null,
      release_date: "2024-03-18",
      vote_average: 8.0,
      vote_count: 1000,
      genre_ids: [10749, 18],
    },
  ],
  bored: [
    {
      id: 21,
      title: "Epic Adventure",
      overview: "A group of unlikely heroes must save the world from an ancient evil.",
      poster_path: "https://example.com/posters/epic_adventure.jpg",
      backdrop_path: null,
      release_date: "2024-07-15",
      vote_average: 8.5,
      vote_count: 1500,
      genre_ids: [28, 12, 14],
    },
    {
      id: 22,
      title: "The Lost Kingdom",
      overview: "An explorer discovers a hidden civilization with advanced technology.",
      poster_path: "https://example.com/posters/lost_kingdom.jpg",
      backdrop_path: null,
      release_date: "2024-03-30",
      vote_average: 8.3,
      vote_count: 1300,
      genre_ids: [12, 14],
    },
    {
      id: 23,
      title: "Maximum Velocity",
      overview: "A professional driver takes on one last dangerous race.",
      poster_path: "https://example.com/posters/maximum_velocity.jpg",
      backdrop_path: null,
      release_date: "2024-05-20",
      vote_average: 7.8,
      vote_count: 950,
      genre_ids: [28, 12],
    },
    {
      id: 24,
      title: "Dragon's Lair",
      overview: "A knight must slay a dragon to save his kingdom from destruction.",
      poster_path: "https://example.com/posters/dragons_lair.jpg",
      backdrop_path: null,
      release_date: "2024-09-10",
      vote_average: 8.0,
      vote_count: 1100,
      genre_ids: [28, 12],
    },
  ],
};
