import type { Movie } from "@/types/movie";

export const mockMovies: Record<string, Movie[]> = {
  happy: [
    {
      id: 1,
      title: "Laugh Trajectory",
      overview: "When an uptight astrophysicist accidentally applies his complex algorithms to a dating app, he unwittingly creates a formula for romantic comedy chaos that transforms his entire research department into relationship gurus.",
      poster_path: "/public/laugh_trajectory.jpeg",
      backdrop_path: null,
      release_date: "2025-02-12",
      vote_average: 9.1,
      vote_count: 2270,
      genre_ids: [35, 10749],
    },
    {
      id: 2,
      title: "Generation Gap Year",
      overview: "After retirement, a tech-averse grandfather joins his influencer granddaughter on her global gap year adventure, becoming an unexpected social media sensation when his old-school wisdom goes viral.",
      poster_path: "https://example.com/posters/generation_gap_year.jpg",
      backdrop_path: null,
      release_date: "2025-01-20",
      vote_average: 8.9,
      vote_count: 1920,
      genre_ids: [35, 10751, 12],
    },
    {
      id: 3,
      title: "Improv Nation",
      overview: "A documentary filmmaker following a struggling improv comedy troupe accidentally captures them stopping a real bank heist with their quick-thinking skills, launching them to fame and into a series of increasingly absurd crime-solving adventures.",
      poster_path: "https://example.com/posters/improv_nation.jpg",
      backdrop_path: null,
      release_date: "2024-12-15",
      vote_average: 8.7,
      vote_count: 1850,
      genre_ids: [35, 80],
    },
    {
      id: 4,
      title: "Reunion Remix",
      overview: "Four former high school bandmates who haven't spoken in twenty years are mistakenly booked as the headline act at a major music festival, giving them one chaotic week to overcome old rivalries and learn to play together again.",
      poster_path: "https://example.com/posters/reunion_remix.jpg",
      backdrop_path: null,
      release_date: "2025-03-18",
      vote_average: 8.8,
      vote_count: 1760,
      genre_ids: [35, 10402],
    },
  ],
  sad: [
    {
      id: 5,
      title: "Echoes of Yesterday",
      overview: "A renowned pianist loses his ability to play after a tragic accident, forcing him to rediscover the meaning of life through teaching a troubled young prodigy.",
      poster_path: "https://example.com/posters/echoes_of_yesterday.jpg",
      backdrop_path: null,
      release_date: "2025-03-12",
      vote_average: 9.1,
      vote_count: 2130,
      genre_ids: [18, 10749],
    },
    {
      id: 6,
      title: "The Last Polaroid",
      overview: "An elderly photographer with early dementia captures his fading memories through a collection of polaroids before they disappear forever.",
      poster_path: "https://example.com/posters/the_last_polaroid.jpg",
      backdrop_path: null,
      release_date: "2025-02-14",
      vote_average: 8.7,
      vote_count: 1870,
      genre_ids: [18, 10749],
    },
    {
      id: 7,
      title: "Silent Harbor",
      overview: "After losing her hearing in a car accident, a marine biologist struggles to reconnect with her work studying whale communications and the husband who blames himself for her condition.",
      poster_path: "https://example.com/posters/silent_harbor.jpg",
      backdrop_path: null,
      release_date: "2025-01-22",
      vote_average: 9.3,
      vote_count: 2450,
      genre_ids: [18, 10749],
    },
    {
      id: 8,
      title: "Letters from Tomorrow",
      overview: "A terminally ill writer creates a series of letters for his daughter to open on significant days of her life long after he's gone.",
      poster_path: "https://example.com/posters/letters_from_tomorrow.jpg",
      backdrop_path: null,
      release_date: "2024-12-05",
      vote_average: 8.9,
      vote_count: 1690,
      genre_ids: [18],
    },
  ],
  thrill: [
    {
      id: 9,
      title: "The Haunting",
      overview: "A family moves into a house with a dark past and begins experiencing terrifying events.",
      poster_path: "https://example.com/posters/haunting.jpg",
      backdrop_path: null,
      release_date: "2024-10-31",
      vote_average: 7.9,
      vote_count: 1100,
      genre_ids: [27, 9648],
    },
    {
      id: 10,
      title: "Night Stalker",
      overview: "A detective hunts a serial killer who only strikes during the full moon.",
      poster_path: "https://example.com/posters/night_stalker.jpg",
      backdrop_path: null,
      release_date: "2024-03-12",
      vote_average: 8.4,
      vote_count: 1300,
      genre_ids: [53, 9648],
    },
    {
      id: 11,
      title: "The Basement",
      overview: "A group of friends discover something horrifying in an abandoned basement.",
      poster_path: "https://example.com/posters/basement.jpg",
      backdrop_path: null,
      release_date: "2024-01-20",
      vote_average: 7.6,
      vote_count: 890,
      genre_ids: [27],
    },
    {
      id: 12,
      title: "Whispers in the Dark",
      overview: "A woman begins hearing voices that lead her to uncover a conspiracy.",
      poster_path: "https://example.com/posters/whispers_in_the_dark.jpg",
      backdrop_path: null,
      release_date: "2024-08-08",
      vote_average: 8.0,
      vote_count: 1050,
      genre_ids: [53, 9648],
    },
  ],

  cry: [
    {
      id: 13,
      title: "Borrowed Time",
      overview: "When a renowned author discovers she has only months to live, she embarks on a journey to mend broken relationships and leave behind a legacy that transcends her bestselling novels.",
      poster_path: "https://example.com/posters/borrowed_time.jpg",
      backdrop_path: null,
      release_date: "2025-04-10",
      vote_average: 9.4,
      vote_count: 2230,
      genre_ids: [18],
    },
    {
      id: 14,
      title: "The Weight of Memory",
      overview: "An Alzheimer's patient fights to hold onto his most precious memories as his mind deteriorates, while his devoted husband documents their 50-year love story through a series of immersive art installations.",
      poster_path: "https://example.com/posters/weight_of_memory.jpg",
      backdrop_path: null,
      release_date: "2025-02-28",
      vote_average: 9.5,
      vote_count: 2680,
      genre_ids: [18],
    },
    {
      id: 15,
      title: "Across the Silence",
      overview: "After losing her twin in a climbing accident, a woman fulfills their shared dream of scaling the world's seven highest peaks, carrying her sister's ashes to scatter at each summit.",
      poster_path: "https://example.com/posters/across_the_silence.jpg",
      backdrop_path: null,
      release_date: "2025-01-15",
      vote_average: 9.2,
      vote_count: 1950,
      genre_ids: [18, 12],
    },
    {
      id: 16,
      title: "The Colors We Leave Behind",
      overview: "A celebrated war photographer returns home after being injured in conflict, only to discover his young daughter doesn't recognize him and his wife has begun to build a life without him.",
      poster_path: "https://example.com/posters/colors_we_leave_behind.jpg",
      backdrop_path: null,
      release_date: "2024-12-12",
      vote_average: 9.0,
      vote_count: 1840,
      genre_ids: [18, 10752],
    },
  ],
  romantic: [
    {
      id: 17,
      title: "Digital Hearts",
      overview: "When two AI ethics researchers develop an algorithm for perfect matchmaking, they become unwitting test subjects when colleagues secretly enter their data, forcing them to confront whether love can be quantified.",
      poster_path: "https://example.com/posters/digital_hearts.jpg",
      backdrop_path: null,
      release_date: "2025-02-14",
      vote_average: 8.6,
      vote_count: 1830,
      genre_ids: [10749, 878],
    },
    {
      id: 18,
      title: "The Impossibility of You",
      overview: "A cynical divorce attorney who's sworn off relationships finds herself inexplicably traveling between parallel universes where she keeps encountering different versions of the same charming man.",
      poster_path: "https://example.com/posters/impossibility_of_you.jpg",
      backdrop_path: null,
      release_date: "2025-01-18",
      vote_average: 8.8,
      vote_count: 2150,
      genre_ids: [10749, 35, 878],
    },
    {
      id: 19,
      title: "Monsoon Letters",
      overview: "A restoration architect renovating an ancient South Asian palace discovers a collection of passionate letters between former royal lovers, while developing feelings for the site's enigmatic historical consultant.",
      poster_path: "https://example.com/posters/monsoon_letters.jpg",
      backdrop_path: null,
      release_date: "2024-11-22",
      vote_average: 9.0,
      vote_count: 1920,
      genre_ids: [10749, 36],
    },
    {
      id: 20,
      title: "Translated",
      overview: "A brilliant linguist developing universal translation technology falls for her research partner who speaks no common languages with her, as they communicate solely through increasingly accurate versions of their AI.",
      poster_path: "https://example.com/posters/translated.jpg",
      backdrop_path: null,
      release_date: "2025-03-12",
      vote_average: 8.7,
      vote_count: 1760,
      genre_ids: [10749, 18, 878],
    },
  ],
  bored: [
    {
      id: 21,
      title: "Quantum Horizon",
      overview: "When a physics experiment tears open the boundary between dimensions, a brilliant but reclusive scientist must lead a team of specialists through increasingly dangerous parallel worlds to seal the breach before reality collapses.",
      poster_path: "https://example.com/posters/quantum_horizon.jpg",
      backdrop_path: null,
      release_date: "2025-03-28",
      vote_average: 9.2,
      vote_count: 2350,
      genre_ids: [28, 12, 878],
    },
    {
      id: 22,
      title: "Eternal Depths",
      overview: "A cutting-edge submarine expedition to the deepest ocean trench discovers a bioluminescent civilization with technology that could revolutionize humanity—or annihilate it if removed from its pressurized environment.",
      poster_path: "https://example.com/posters/eternal_depths.jpg",
      backdrop_path: null,
      release_date: "2025-01-15",
      vote_average: 8.9,
      vote_count: 1980,
      genre_ids: [12, 878, 9648],
    },
    {
      id: 23,
      title: "Hyperdrive",
      overview: "In a near-future where illegal AI-controlled racing has become the world's most dangerous sport, a disgraced former champion must team up with an experimental sentient vehicle to infiltrate a global criminal syndicate.",
      poster_path: "https://example.com/posters/hyperdrive.jpg",
      backdrop_path: null,
      release_date: "2024-12-10",
      vote_average: 8.7,
      vote_count: 1860,
      genre_ids: [28, 12, 878],
    },
    {
      id: 24,
      title: "Obsidian Crown",
      overview: "After discovering she carries the bloodline of an ancient warrior dynasty, a museum curator must master forgotten martial arts to reclaim a powerful artifact from a ruthless paramilitary organization bent on world domination.",
      poster_path: "https://example.com/posters/obsidian_crown.jpg",
      backdrop_path: null,
      release_date: "2025-02-22",
      vote_average: 8.8,
      vote_count: 2140,
      genre_ids: [28, 12, 14],
    },
  ],
};
